# Generated by Django 3.1.2 on 2020-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futuresymbol', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('expmonthyear', models.DateField()),
                ('closing_price', models.FloatField()),
                ('change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('trades', models.IntegerField()),
                ('fixing_price', models.FloatField()),
                ('open_interest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionsymbol', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('optiontype', models.CharField(max_length=4)),
                ('strike', models.FloatField()),
                ('expmonthdate', models.DateField()),
                ('closing_price', models.FloatField()),
                ('change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('trades', models.IntegerField()),
                ('fixing_price', models.FloatField()),
                ('open_interest', models.IntegerField()),
                ('stock', models.CharField(max_length=10)),
                ('imp_vol', models.FloatField()),
                ('atm_strike', models.FloatField()),
                ('frontexpdate', models.DateField()),
                ('expmonth_atm_impvol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
