# Generated by Django 3.1.2 on 2020-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0002_auto_20201019_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='asset',
            field=models.CharField(choices=[('FTSE', 'FTSE'), ('ALPHA', 'ALPHA'), ('HTO', 'HTO'), ('ETE', 'ETE'), ('OPAP', 'OPAP'), ('PPC', 'PPC'), ('TPEIR', 'TPEIR')], max_length=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='optiontype',
            field=models.CharField(choices=[('c', 'Call'), ('p', 'Put')], max_length=1),
        ),
    ]
