# Generated by Django 3.1.2 on 2020-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0003_auto_20201027_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='asset',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='optiontype',
            field=models.CharField(max_length=4),
        ),
    ]
