# Generated by Django 2.0.1 on 2020-11-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0004_auto_20201028_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'get_latest_by': 'date'},
        ),
    ]
